spring:
  datasource:
          url: jdbc:mysql://localhost:3306/thejavaclass
          username: root
          password: Dew2339
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port:8080